apiVersion: apps/v1beta1 #  for k8s versions before 1.9.0 use apps/v1beta2  and before 1.8.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: lifesense-qa2-redis-slave
  namespace: base
spec:
  selector:
    matchLabels:
      app: redis
      role: slave
      tier: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
        role: slave
        tier: backend
    spec:
      containers:
      - name: slave
        image: vflong/redis-slave
        resources:
          requests:
            cpu: 100m
            memory: 1024Mi
        env:
        - name: GET_HOSTS_FROM
          value: dns
          # If your cluster config does not include a dns service, then to
          # instead access an environment variable to find the master
          # service's host, comment out the 'value: dns' line above, and
          # uncomment the line below:
          # value: env
        ports:
        - containerPort: 6379
        volumeMounts:
          - name: "redis-data"
            mountPath: "/data"
      volumes:
        - name: "redis-data"
          persistentVolumeClaim:
            claimName: redis-data-lifesense-qa2-redis-slave
