apiVersion: v1
kind: Service
metadata:
  name: lifesense-qa-redis-master
  namespace: base
  labels:
    app: lifesense-qa-redis
    role: master
    tier: backend
spec:
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    app: lifesense-qa-redis
    role: master
    tier: backend
