apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-vol3
  labels:
    path: nfsshare3
    type: redis-nfs
    app: redis
    podindex: "2"
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 10.9.34.61
    path: "/data/nfs/n3"



